# Generated by Django 5.1.7 on 2025-03-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao_produto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
