# Generated by Django 5.1.7 on 2025-05-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_pedido'),
        ('catalog', '0004_produto_categoria'),
    ]

    operations = [
    ]
